// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package conversations_test

import (
	"context"
	"errors"
	"os"
	"testing"

	"github.com/stainless-sdks/hubspot-sdk-go"
	"github.com/stainless-sdks/hubspot-sdk-go/conversations"
	"github.com/stainless-sdks/hubspot-sdk-go/internal/testutil"
	"github.com/stainless-sdks/hubspot-sdk-go/option"
)

func TestCustomChannelNewWithOptionalParams(t *testing.T) {
	t.Skip("Prism tests are disabled")
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := hubspotsdk.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAccessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"),
	)
	_, err := client.Conversations.CustomChannels.New(context.TODO(), conversations.CustomChannelNewParams{
		Capabilities: map[string]any{
			"0":   map[string]interface{}{},
			"1":   map[string]interface{}{},
			"2":   map[string]interface{}{},
			"3":   map[string]interface{}{},
			"4":   map[string]interface{}{},
			"5":   map[string]interface{}{},
			"6":   map[string]interface{}{},
			"7":   map[string]interface{}{},
			"8":   map[string]interface{}{},
			"9":   map[string]interface{}{},
			"10":  map[string]interface{}{},
			"11":  map[string]interface{}{},
			"12":  map[string]interface{}{},
			"13":  map[string]interface{}{},
			"14":  map[string]interface{}{},
			"15":  map[string]interface{}{},
			"16":  map[string]interface{}{},
			"17":  map[string]interface{}{},
			"18":  map[string]interface{}{},
			"19":  map[string]interface{}{},
			"20":  map[string]interface{}{},
			"21":  map[string]interface{}{},
			"22":  map[string]interface{}{},
			"23":  map[string]interface{}{},
			"24":  map[string]interface{}{},
			"25":  map[string]interface{}{},
			"26":  map[string]interface{}{},
			"27":  map[string]interface{}{},
			"28":  map[string]interface{}{},
			"29":  map[string]interface{}{},
			"30":  map[string]interface{}{},
			"31":  map[string]interface{}{},
			"32":  map[string]interface{}{},
			"33":  map[string]interface{}{},
			"34":  map[string]interface{}{},
			"35":  map[string]interface{}{},
			"36":  map[string]interface{}{},
			"37":  map[string]interface{}{},
			"38":  map[string]interface{}{},
			"39":  map[string]interface{}{},
			"40":  map[string]interface{}{},
			"41":  map[string]interface{}{},
			"42":  map[string]interface{}{},
			"43":  map[string]interface{}{},
			"44":  map[string]interface{}{},
			"45":  map[string]interface{}{},
			"46":  map[string]interface{}{},
			"47":  map[string]interface{}{},
			"48":  map[string]interface{}{},
			"49":  map[string]interface{}{},
			"50":  map[string]interface{}{},
			"51":  map[string]interface{}{},
			"52":  map[string]interface{}{},
			"53":  map[string]interface{}{},
			"54":  map[string]interface{}{},
			"55":  map[string]interface{}{},
			"56":  map[string]interface{}{},
			"57":  map[string]interface{}{},
			"58":  map[string]interface{}{},
			"59":  map[string]interface{}{},
			"60":  map[string]interface{}{},
			"61":  map[string]interface{}{},
			"62":  map[string]interface{}{},
			"63":  map[string]interface{}{},
			"64":  map[string]interface{}{},
			"65":  map[string]interface{}{},
			"66":  map[string]interface{}{},
			"67":  map[string]interface{}{},
			"68":  map[string]interface{}{},
			"69":  map[string]interface{}{},
			"70":  map[string]interface{}{},
			"71":  map[string]interface{}{},
			"72":  map[string]interface{}{},
			"73":  map[string]interface{}{},
			"74":  map[string]interface{}{},
			"75":  map[string]interface{}{},
			"76":  map[string]interface{}{},
			"77":  map[string]interface{}{},
			"78":  map[string]interface{}{},
			"79":  map[string]interface{}{},
			"80":  map[string]interface{}{},
			"81":  map[string]interface{}{},
			"82":  map[string]interface{}{},
			"83":  map[string]interface{}{},
			"84":  map[string]interface{}{},
			"85":  map[string]interface{}{},
			"86":  map[string]interface{}{},
			"87":  map[string]interface{}{},
			"88":  map[string]interface{}{},
			"89":  map[string]interface{}{},
			"90":  map[string]interface{}{},
			"91":  map[string]interface{}{},
			"92":  map[string]interface{}{},
			"93":  map[string]interface{}{},
			"94":  map[string]interface{}{},
			"95":  map[string]interface{}{},
			"96":  map[string]interface{}{},
			"97":  map[string]interface{}{},
			"98":  map[string]interface{}{},
			"99":  map[string]interface{}{},
			"100": map[string]interface{}{},
			"101": map[string]interface{}{},
			"102": map[string]interface{}{},
			"103": map[string]interface{}{},
			"104": map[string]interface{}{},
			"105": map[string]interface{}{},
			"106": map[string]interface{}{},
			"107": map[string]interface{}{},
			"108": map[string]interface{}{},
			"109": map[string]interface{}{},
			"110": map[string]interface{}{},
			"111": map[string]interface{}{},
			"112": map[string]interface{}{},
			"113": map[string]interface{}{},
			"114": map[string]interface{}{},
			"115": map[string]interface{}{},
			"116": map[string]interface{}{},
			"117": map[string]interface{}{},
			"118": map[string]interface{}{},
			"119": map[string]interface{}{},
			"120": map[string]interface{}{},
			"121": map[string]interface{}{},
			"122": map[string]interface{}{},
			"123": map[string]interface{}{},
			"124": map[string]interface{}{},
			"125": map[string]interface{}{},
			"126": map[string]interface{}{},
			"127": map[string]interface{}{},
			"128": map[string]interface{}{},
			"129": map[string]interface{}{},
			"130": map[string]interface{}{},
			"131": map[string]interface{}{},
			"132": map[string]interface{}{},
			"133": map[string]interface{}{},
			"134": map[string]interface{}{},
			"135": map[string]interface{}{},
			"136": map[string]interface{}{},
			"137": map[string]interface{}{},
			"138": map[string]interface{}{},
			"139": map[string]interface{}{},
			"140": map[string]interface{}{},
			"141": map[string]interface{}{},
			"142": map[string]interface{}{},
			"143": map[string]interface{}{},
			"144": map[string]interface{}{},
			"145": map[string]interface{}{},
			"146": map[string]interface{}{},
			"147": map[string]interface{}{},
			"148": map[string]interface{}{},
			"149": map[string]interface{}{},
			"150": map[string]interface{}{},
			"151": map[string]interface{}{},
			"152": map[string]interface{}{},
			"153": map[string]interface{}{},
			"154": map[string]interface{}{},
			"155": map[string]interface{}{},
			"156": map[string]interface{}{},
			"157": map[string]interface{}{},
			"158": map[string]interface{}{},
			"159": map[string]interface{}{},
			"160": map[string]interface{}{},
			"161": map[string]interface{}{},
			"162": map[string]interface{}{},
			"163": map[string]interface{}{},
			"164": map[string]interface{}{},
			"165": map[string]interface{}{},
			"166": map[string]interface{}{},
			"167": map[string]interface{}{},
			"168": map[string]interface{}{},
			"169": map[string]interface{}{},
			"170": map[string]interface{}{},
			"171": map[string]interface{}{},
			"172": map[string]interface{}{},
			"173": map[string]interface{}{},
			"174": map[string]interface{}{},
			"175": map[string]interface{}{},
			"176": map[string]interface{}{},
			"177": map[string]interface{}{},
			"178": map[string]interface{}{},
			"179": map[string]interface{}{},
			"180": map[string]interface{}{},
			"181": map[string]interface{}{},
			"182": map[string]interface{}{},
			"183": map[string]interface{}{},
			"184": map[string]interface{}{},
			"185": map[string]interface{}{},
			"186": map[string]interface{}{},
			"187": map[string]interface{}{},
			"188": map[string]interface{}{},
			"189": map[string]interface{}{},
			"190": map[string]interface{}{},
			"191": map[string]interface{}{},
			"192": map[string]interface{}{},
			"193": map[string]interface{}{},
			"194": map[string]interface{}{},
			"195": map[string]interface{}{},
			"196": map[string]interface{}{},
			"197": map[string]interface{}{},
			"198": map[string]interface{}{},
			"199": map[string]interface{}{},
			"200": map[string]interface{}{},
			"201": map[string]interface{}{},
			"202": map[string]interface{}{},
			"203": map[string]interface{}{},
			"204": map[string]interface{}{},
			"205": map[string]interface{}{},
			"206": map[string]interface{}{},
			"207": map[string]interface{}{},
			"208": map[string]interface{}{},
			"209": map[string]interface{}{},
			"210": map[string]interface{}{},
			"211": map[string]interface{}{},
			"212": map[string]interface{}{},
			"213": map[string]interface{}{},
			"214": map[string]interface{}{},
			"215": map[string]interface{}{},
			"216": map[string]interface{}{},
			"217": map[string]interface{}{},
			"218": map[string]interface{}{},
			"219": map[string]interface{}{},
			"220": map[string]interface{}{},
			"221": map[string]interface{}{},
			"222": map[string]interface{}{},
			"223": map[string]interface{}{},
			"224": map[string]interface{}{},
			"225": map[string]interface{}{},
			"226": map[string]interface{}{},
			"227": map[string]interface{}{},
			"228": map[string]interface{}{},
			"229": map[string]interface{}{},
			"230": map[string]interface{}{},
			"231": map[string]interface{}{},
			"232": map[string]interface{}{},
			"233": map[string]interface{}{},
			"234": map[string]interface{}{},
			"235": map[string]interface{}{},
			"236": map[string]interface{}{},
			"237": map[string]interface{}{},
			"238": map[string]interface{}{},
			"239": map[string]interface{}{},
			"240": map[string]interface{}{},
			"241": map[string]interface{}{},
			"242": map[string]interface{}{},
			"243": map[string]interface{}{},
			"244": map[string]interface{}{},
			"245": map[string]interface{}{},
			"246": map[string]interface{}{},
			"247": map[string]interface{}{},
			"248": map[string]interface{}{},
			"249": map[string]interface{}{},
			"250": map[string]interface{}{},
			"251": map[string]interface{}{},
			"252": map[string]interface{}{},
			"253": map[string]interface{}{},
			"254": map[string]interface{}{},
			"255": map[string]interface{}{},
			"256": map[string]interface{}{},
			"257": map[string]interface{}{},
			"258": map[string]interface{}{},
			"259": map[string]interface{}{},
			"260": map[string]interface{}{},
			"261": map[string]interface{}{},
			"262": map[string]interface{}{},
			"263": map[string]interface{}{},
			"264": map[string]interface{}{},
			"265": map[string]interface{}{},
			"266": map[string]interface{}{},
			"267": map[string]interface{}{},
			"268": map[string]interface{}{},
			"269": map[string]interface{}{},
			"270": map[string]interface{}{},
			"271": map[string]interface{}{},
			"272": map[string]interface{}{},
			"273": map[string]interface{}{},
			"274": map[string]interface{}{},
			"275": map[string]interface{}{},
			"276": map[string]interface{}{},
			"277": map[string]interface{}{},
			"278": map[string]interface{}{},
			"279": map[string]interface{}{},
			"280": map[string]interface{}{},
			"281": map[string]interface{}{},
			"282": map[string]interface{}{},
			"283": map[string]interface{}{},
			"284": map[string]interface{}{},
			"285": map[string]interface{}{},
			"286": map[string]interface{}{},
			"287": map[string]interface{}{},
			"288": map[string]interface{}{},
			"289": map[string]interface{}{},
			"290": map[string]interface{}{},
			"291": map[string]interface{}{},
			"292": map[string]interface{}{},
			"293": map[string]interface{}{},
			"294": map[string]interface{}{},
			"295": map[string]interface{}{},
			"296": map[string]interface{}{},
			"297": map[string]interface{}{},
			"298": map[string]interface{}{},
			"299": map[string]interface{}{},
			"300": map[string]interface{}{},
			"301": map[string]interface{}{},
			"302": map[string]interface{}{},
			"303": map[string]interface{}{},
			"304": map[string]interface{}{},
			"305": map[string]interface{}{},
			"306": map[string]interface{}{},
			"307": map[string]interface{}{},
			"308": map[string]interface{}{},
			"309": map[string]interface{}{},
			"310": map[string]interface{}{},
			"311": map[string]interface{}{},
			"312": map[string]interface{}{},
			"313": map[string]interface{}{},
			"314": map[string]interface{}{},
			"315": map[string]interface{}{},
			"316": map[string]interface{}{},
			"317": map[string]interface{}{},
			"318": map[string]interface{}{},
			"319": map[string]interface{}{},
			"320": map[string]interface{}{},
			"321": map[string]interface{}{},
			"322": map[string]interface{}{},
			"323": map[string]interface{}{},
			"324": map[string]interface{}{},
			"325": map[string]interface{}{},
			"326": map[string]interface{}{},
			"327": map[string]interface{}{},
			"328": map[string]interface{}{},
			"329": map[string]interface{}{},
			"330": map[string]interface{}{},
			"331": map[string]interface{}{},
			"332": map[string]interface{}{},
			"333": map[string]interface{}{},
			"334": map[string]interface{}{},
			"335": map[string]interface{}{},
			"336": map[string]interface{}{},
			"337": map[string]interface{}{},
			"338": map[string]interface{}{},
			"339": map[string]interface{}{},
			"340": map[string]interface{}{},
			"341": map[string]interface{}{},
			"342": map[string]interface{}{},
			"343": map[string]interface{}{},
			"344": map[string]interface{}{},
			"345": map[string]interface{}{},
			"346": map[string]interface{}{},
			"347": map[string]interface{}{},
			"348": map[string]interface{}{},
			"349": map[string]interface{}{},
			"350": map[string]interface{}{},
			"351": map[string]interface{}{},
			"352": map[string]interface{}{},
			"353": map[string]interface{}{},
			"354": map[string]interface{}{},
			"355": map[string]interface{}{},
			"356": map[string]interface{}{},
			"357": map[string]interface{}{},
			"358": map[string]interface{}{},
			"359": map[string]interface{}{},
			"360": map[string]interface{}{},
			"361": map[string]interface{}{},
			"362": map[string]interface{}{},
			"363": map[string]interface{}{},
			"364": map[string]interface{}{},
			"365": map[string]interface{}{},
			"366": map[string]interface{}{},
			"367": map[string]interface{}{},
			"368": map[string]interface{}{},
			"369": map[string]interface{}{},
			"370": map[string]interface{}{},
			"371": map[string]interface{}{},
			"372": map[string]interface{}{},
			"373": map[string]interface{}{},
			"374": map[string]interface{}{},
			"375": map[string]interface{}{},
			"376": map[string]interface{}{},
			"377": map[string]interface{}{},
			"378": map[string]interface{}{},
			"379": map[string]interface{}{},
			"380": map[string]interface{}{},
			"381": map[string]interface{}{},
			"382": map[string]interface{}{},
			"383": map[string]interface{}{},
			"384": map[string]interface{}{},
			"385": map[string]interface{}{},
			"386": map[string]interface{}{},
			"387": map[string]interface{}{},
			"388": map[string]interface{}{},
			"389": map[string]interface{}{},
			"390": map[string]interface{}{},
			"391": map[string]interface{}{},
			"392": map[string]interface{}{},
			"393": map[string]interface{}{},
			"394": map[string]interface{}{},
			"395": map[string]interface{}{},
			"396": map[string]interface{}{},
			"397": map[string]interface{}{},
			"398": map[string]interface{}{},
			"399": map[string]interface{}{},
			"400": map[string]interface{}{},
			"401": map[string]interface{}{},
			"402": map[string]interface{}{},
			"403": map[string]interface{}{},
			"404": map[string]interface{}{},
			"405": map[string]interface{}{},
			"406": map[string]interface{}{},
			"407": map[string]interface{}{},
			"408": map[string]interface{}{},
			"409": map[string]interface{}{},
			"410": map[string]interface{}{},
			"411": map[string]interface{}{},
			"412": map[string]interface{}{},
			"413": map[string]interface{}{},
			"414": map[string]interface{}{},
			"415": map[string]interface{}{},
			"416": map[string]interface{}{},
			"417": map[string]interface{}{},
			"418": map[string]interface{}{},
			"419": map[string]interface{}{},
			"420": map[string]interface{}{},
			"421": map[string]interface{}{},
			"422": map[string]interface{}{},
			"423": map[string]interface{}{},
			"424": map[string]interface{}{},
			"425": map[string]interface{}{},
			"426": map[string]interface{}{},
			"427": map[string]interface{}{},
			"428": map[string]interface{}{},
			"429": map[string]interface{}{},
			"430": map[string]interface{}{},
			"431": map[string]interface{}{},
			"432": map[string]interface{}{},
			"433": map[string]interface{}{},
			"434": map[string]interface{}{},
			"435": map[string]interface{}{},
			"436": map[string]interface{}{},
			"437": map[string]interface{}{},
			"438": map[string]interface{}{},
			"439": map[string]interface{}{},
			"440": map[string]interface{}{},
			"441": map[string]interface{}{},
			"442": map[string]interface{}{},
			"443": map[string]interface{}{},
			"444": map[string]interface{}{},
			"445": map[string]interface{}{},
			"446": map[string]interface{}{},
			"447": map[string]interface{}{},
			"448": map[string]interface{}{},
			"449": map[string]interface{}{},
			"450": map[string]interface{}{},
			"451": map[string]interface{}{},
			"452": map[string]interface{}{},
			"453": map[string]interface{}{},
			"454": map[string]interface{}{},
		},
		Name:                                "name",
		ChannelAccountConnectionRedirectURL: hubspotsdk.String("channelAccountConnectionRedirectUrl"),
		ChannelDescription:                  hubspotsdk.String("channelDescription"),
		ChannelLogoURL:                      hubspotsdk.String("channelLogoUrl"),
		WebhookURL:                          hubspotsdk.String("webhookUrl"),
	})
	if err != nil {
		var apierr *hubspotsdk.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestCustomChannelUpdateWithOptionalParams(t *testing.T) {
	t.Skip("Prism tests are disabled")
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := hubspotsdk.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAccessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"),
	)
	_, err := client.Conversations.CustomChannels.Update(
		context.TODO(),
		"channelId",
		conversations.CustomChannelUpdateParams{
			Capabilities: map[string]any{
				"0":   map[string]interface{}{},
				"1":   map[string]interface{}{},
				"2":   map[string]interface{}{},
				"3":   map[string]interface{}{},
				"4":   map[string]interface{}{},
				"5":   map[string]interface{}{},
				"6":   map[string]interface{}{},
				"7":   map[string]interface{}{},
				"8":   map[string]interface{}{},
				"9":   map[string]interface{}{},
				"10":  map[string]interface{}{},
				"11":  map[string]interface{}{},
				"12":  map[string]interface{}{},
				"13":  map[string]interface{}{},
				"14":  map[string]interface{}{},
				"15":  map[string]interface{}{},
				"16":  map[string]interface{}{},
				"17":  map[string]interface{}{},
				"18":  map[string]interface{}{},
				"19":  map[string]interface{}{},
				"20":  map[string]interface{}{},
				"21":  map[string]interface{}{},
				"22":  map[string]interface{}{},
				"23":  map[string]interface{}{},
				"24":  map[string]interface{}{},
				"25":  map[string]interface{}{},
				"26":  map[string]interface{}{},
				"27":  map[string]interface{}{},
				"28":  map[string]interface{}{},
				"29":  map[string]interface{}{},
				"30":  map[string]interface{}{},
				"31":  map[string]interface{}{},
				"32":  map[string]interface{}{},
				"33":  map[string]interface{}{},
				"34":  map[string]interface{}{},
				"35":  map[string]interface{}{},
				"36":  map[string]interface{}{},
				"37":  map[string]interface{}{},
				"38":  map[string]interface{}{},
				"39":  map[string]interface{}{},
				"40":  map[string]interface{}{},
				"41":  map[string]interface{}{},
				"42":  map[string]interface{}{},
				"43":  map[string]interface{}{},
				"44":  map[string]interface{}{},
				"45":  map[string]interface{}{},
				"46":  map[string]interface{}{},
				"47":  map[string]interface{}{},
				"48":  map[string]interface{}{},
				"49":  map[string]interface{}{},
				"50":  map[string]interface{}{},
				"51":  map[string]interface{}{},
				"52":  map[string]interface{}{},
				"53":  map[string]interface{}{},
				"54":  map[string]interface{}{},
				"55":  map[string]interface{}{},
				"56":  map[string]interface{}{},
				"57":  map[string]interface{}{},
				"58":  map[string]interface{}{},
				"59":  map[string]interface{}{},
				"60":  map[string]interface{}{},
				"61":  map[string]interface{}{},
				"62":  map[string]interface{}{},
				"63":  map[string]interface{}{},
				"64":  map[string]interface{}{},
				"65":  map[string]interface{}{},
				"66":  map[string]interface{}{},
				"67":  map[string]interface{}{},
				"68":  map[string]interface{}{},
				"69":  map[string]interface{}{},
				"70":  map[string]interface{}{},
				"71":  map[string]interface{}{},
				"72":  map[string]interface{}{},
				"73":  map[string]interface{}{},
				"74":  map[string]interface{}{},
				"75":  map[string]interface{}{},
				"76":  map[string]interface{}{},
				"77":  map[string]interface{}{},
				"78":  map[string]interface{}{},
				"79":  map[string]interface{}{},
				"80":  map[string]interface{}{},
				"81":  map[string]interface{}{},
				"82":  map[string]interface{}{},
				"83":  map[string]interface{}{},
				"84":  map[string]interface{}{},
				"85":  map[string]interface{}{},
				"86":  map[string]interface{}{},
				"87":  map[string]interface{}{},
				"88":  map[string]interface{}{},
				"89":  map[string]interface{}{},
				"90":  map[string]interface{}{},
				"91":  map[string]interface{}{},
				"92":  map[string]interface{}{},
				"93":  map[string]interface{}{},
				"94":  map[string]interface{}{},
				"95":  map[string]interface{}{},
				"96":  map[string]interface{}{},
				"97":  map[string]interface{}{},
				"98":  map[string]interface{}{},
				"99":  map[string]interface{}{},
				"100": map[string]interface{}{},
				"101": map[string]interface{}{},
				"102": map[string]interface{}{},
				"103": map[string]interface{}{},
				"104": map[string]interface{}{},
				"105": map[string]interface{}{},
				"106": map[string]interface{}{},
				"107": map[string]interface{}{},
				"108": map[string]interface{}{},
				"109": map[string]interface{}{},
				"110": map[string]interface{}{},
				"111": map[string]interface{}{},
				"112": map[string]interface{}{},
				"113": map[string]interface{}{},
				"114": map[string]interface{}{},
				"115": map[string]interface{}{},
				"116": map[string]interface{}{},
				"117": map[string]interface{}{},
				"118": map[string]interface{}{},
				"119": map[string]interface{}{},
				"120": map[string]interface{}{},
				"121": map[string]interface{}{},
				"122": map[string]interface{}{},
				"123": map[string]interface{}{},
				"124": map[string]interface{}{},
				"125": map[string]interface{}{},
				"126": map[string]interface{}{},
				"127": map[string]interface{}{},
				"128": map[string]interface{}{},
				"129": map[string]interface{}{},
				"130": map[string]interface{}{},
				"131": map[string]interface{}{},
				"132": map[string]interface{}{},
				"133": map[string]interface{}{},
				"134": map[string]interface{}{},
				"135": map[string]interface{}{},
				"136": map[string]interface{}{},
				"137": map[string]interface{}{},
				"138": map[string]interface{}{},
				"139": map[string]interface{}{},
				"140": map[string]interface{}{},
				"141": map[string]interface{}{},
				"142": map[string]interface{}{},
				"143": map[string]interface{}{},
				"144": map[string]interface{}{},
				"145": map[string]interface{}{},
				"146": map[string]interface{}{},
				"147": map[string]interface{}{},
				"148": map[string]interface{}{},
				"149": map[string]interface{}{},
				"150": map[string]interface{}{},
				"151": map[string]interface{}{},
				"152": map[string]interface{}{},
				"153": map[string]interface{}{},
				"154": map[string]interface{}{},
				"155": map[string]interface{}{},
				"156": map[string]interface{}{},
				"157": map[string]interface{}{},
				"158": map[string]interface{}{},
				"159": map[string]interface{}{},
				"160": map[string]interface{}{},
				"161": map[string]interface{}{},
				"162": map[string]interface{}{},
				"163": map[string]interface{}{},
				"164": map[string]interface{}{},
				"165": map[string]interface{}{},
				"166": map[string]interface{}{},
				"167": map[string]interface{}{},
				"168": map[string]interface{}{},
				"169": map[string]interface{}{},
				"170": map[string]interface{}{},
				"171": map[string]interface{}{},
				"172": map[string]interface{}{},
				"173": map[string]interface{}{},
				"174": map[string]interface{}{},
				"175": map[string]interface{}{},
				"176": map[string]interface{}{},
				"177": map[string]interface{}{},
				"178": map[string]interface{}{},
				"179": map[string]interface{}{},
				"180": map[string]interface{}{},
				"181": map[string]interface{}{},
				"182": map[string]interface{}{},
				"183": map[string]interface{}{},
				"184": map[string]interface{}{},
				"185": map[string]interface{}{},
				"186": map[string]interface{}{},
				"187": map[string]interface{}{},
				"188": map[string]interface{}{},
				"189": map[string]interface{}{},
				"190": map[string]interface{}{},
				"191": map[string]interface{}{},
				"192": map[string]interface{}{},
				"193": map[string]interface{}{},
				"194": map[string]interface{}{},
				"195": map[string]interface{}{},
				"196": map[string]interface{}{},
				"197": map[string]interface{}{},
				"198": map[string]interface{}{},
				"199": map[string]interface{}{},
				"200": map[string]interface{}{},
				"201": map[string]interface{}{},
				"202": map[string]interface{}{},
				"203": map[string]interface{}{},
				"204": map[string]interface{}{},
				"205": map[string]interface{}{},
				"206": map[string]interface{}{},
				"207": map[string]interface{}{},
				"208": map[string]interface{}{},
				"209": map[string]interface{}{},
				"210": map[string]interface{}{},
				"211": map[string]interface{}{},
				"212": map[string]interface{}{},
				"213": map[string]interface{}{},
				"214": map[string]interface{}{},
				"215": map[string]interface{}{},
				"216": map[string]interface{}{},
				"217": map[string]interface{}{},
				"218": map[string]interface{}{},
				"219": map[string]interface{}{},
				"220": map[string]interface{}{},
				"221": map[string]interface{}{},
				"222": map[string]interface{}{},
				"223": map[string]interface{}{},
				"224": map[string]interface{}{},
				"225": map[string]interface{}{},
				"226": map[string]interface{}{},
				"227": map[string]interface{}{},
				"228": map[string]interface{}{},
				"229": map[string]interface{}{},
				"230": map[string]interface{}{},
				"231": map[string]interface{}{},
				"232": map[string]interface{}{},
				"233": map[string]interface{}{},
				"234": map[string]interface{}{},
				"235": map[string]interface{}{},
				"236": map[string]interface{}{},
				"237": map[string]interface{}{},
				"238": map[string]interface{}{},
				"239": map[string]interface{}{},
				"240": map[string]interface{}{},
				"241": map[string]interface{}{},
				"242": map[string]interface{}{},
				"243": map[string]interface{}{},
				"244": map[string]interface{}{},
				"245": map[string]interface{}{},
				"246": map[string]interface{}{},
				"247": map[string]interface{}{},
				"248": map[string]interface{}{},
				"249": map[string]interface{}{},
				"250": map[string]interface{}{},
				"251": map[string]interface{}{},
				"252": map[string]interface{}{},
				"253": map[string]interface{}{},
				"254": map[string]interface{}{},
				"255": map[string]interface{}{},
				"256": map[string]interface{}{},
				"257": map[string]interface{}{},
				"258": map[string]interface{}{},
				"259": map[string]interface{}{},
				"260": map[string]interface{}{},
				"261": map[string]interface{}{},
				"262": map[string]interface{}{},
				"263": map[string]interface{}{},
				"264": map[string]interface{}{},
				"265": map[string]interface{}{},
				"266": map[string]interface{}{},
				"267": map[string]interface{}{},
				"268": map[string]interface{}{},
				"269": map[string]interface{}{},
				"270": map[string]interface{}{},
				"271": map[string]interface{}{},
				"272": map[string]interface{}{},
				"273": map[string]interface{}{},
				"274": map[string]interface{}{},
				"275": map[string]interface{}{},
				"276": map[string]interface{}{},
				"277": map[string]interface{}{},
				"278": map[string]interface{}{},
				"279": map[string]interface{}{},
				"280": map[string]interface{}{},
				"281": map[string]interface{}{},
				"282": map[string]interface{}{},
				"283": map[string]interface{}{},
				"284": map[string]interface{}{},
				"285": map[string]interface{}{},
				"286": map[string]interface{}{},
				"287": map[string]interface{}{},
				"288": map[string]interface{}{},
				"289": map[string]interface{}{},
				"290": map[string]interface{}{},
				"291": map[string]interface{}{},
				"292": map[string]interface{}{},
				"293": map[string]interface{}{},
				"294": map[string]interface{}{},
				"295": map[string]interface{}{},
				"296": map[string]interface{}{},
				"297": map[string]interface{}{},
				"298": map[string]interface{}{},
				"299": map[string]interface{}{},
				"300": map[string]interface{}{},
				"301": map[string]interface{}{},
				"302": map[string]interface{}{},
				"303": map[string]interface{}{},
				"304": map[string]interface{}{},
				"305": map[string]interface{}{},
				"306": map[string]interface{}{},
				"307": map[string]interface{}{},
				"308": map[string]interface{}{},
				"309": map[string]interface{}{},
				"310": map[string]interface{}{},
				"311": map[string]interface{}{},
				"312": map[string]interface{}{},
				"313": map[string]interface{}{},
				"314": map[string]interface{}{},
				"315": map[string]interface{}{},
				"316": map[string]interface{}{},
				"317": map[string]interface{}{},
				"318": map[string]interface{}{},
				"319": map[string]interface{}{},
				"320": map[string]interface{}{},
				"321": map[string]interface{}{},
				"322": map[string]interface{}{},
				"323": map[string]interface{}{},
				"324": map[string]interface{}{},
				"325": map[string]interface{}{},
				"326": map[string]interface{}{},
				"327": map[string]interface{}{},
				"328": map[string]interface{}{},
				"329": map[string]interface{}{},
				"330": map[string]interface{}{},
				"331": map[string]interface{}{},
				"332": map[string]interface{}{},
				"333": map[string]interface{}{},
				"334": map[string]interface{}{},
				"335": map[string]interface{}{},
				"336": map[string]interface{}{},
				"337": map[string]interface{}{},
				"338": map[string]interface{}{},
				"339": map[string]interface{}{},
				"340": map[string]interface{}{},
				"341": map[string]interface{}{},
				"342": map[string]interface{}{},
				"343": map[string]interface{}{},
				"344": map[string]interface{}{},
				"345": map[string]interface{}{},
				"346": map[string]interface{}{},
				"347": map[string]interface{}{},
				"348": map[string]interface{}{},
				"349": map[string]interface{}{},
				"350": map[string]interface{}{},
				"351": map[string]interface{}{},
				"352": map[string]interface{}{},
				"353": map[string]interface{}{},
				"354": map[string]interface{}{},
				"355": map[string]interface{}{},
				"356": map[string]interface{}{},
				"357": map[string]interface{}{},
				"358": map[string]interface{}{},
				"359": map[string]interface{}{},
				"360": map[string]interface{}{},
				"361": map[string]interface{}{},
				"362": map[string]interface{}{},
				"363": map[string]interface{}{},
				"364": map[string]interface{}{},
				"365": map[string]interface{}{},
				"366": map[string]interface{}{},
				"367": map[string]interface{}{},
				"368": map[string]interface{}{},
				"369": map[string]interface{}{},
				"370": map[string]interface{}{},
				"371": map[string]interface{}{},
				"372": map[string]interface{}{},
				"373": map[string]interface{}{},
				"374": map[string]interface{}{},
				"375": map[string]interface{}{},
				"376": map[string]interface{}{},
				"377": map[string]interface{}{},
				"378": map[string]interface{}{},
				"379": map[string]interface{}{},
				"380": map[string]interface{}{},
				"381": map[string]interface{}{},
				"382": map[string]interface{}{},
				"383": map[string]interface{}{},
				"384": map[string]interface{}{},
				"385": map[string]interface{}{},
				"386": map[string]interface{}{},
				"387": map[string]interface{}{},
				"388": map[string]interface{}{},
				"389": map[string]interface{}{},
				"390": map[string]interface{}{},
				"391": map[string]interface{}{},
				"392": map[string]interface{}{},
				"393": map[string]interface{}{},
				"394": map[string]interface{}{},
				"395": map[string]interface{}{},
				"396": map[string]interface{}{},
				"397": map[string]interface{}{},
				"398": map[string]interface{}{},
				"399": map[string]interface{}{},
				"400": map[string]interface{}{},
				"401": map[string]interface{}{},
				"402": map[string]interface{}{},
				"403": map[string]interface{}{},
				"404": map[string]interface{}{},
				"405": map[string]interface{}{},
				"406": map[string]interface{}{},
				"407": map[string]interface{}{},
				"408": map[string]interface{}{},
				"409": map[string]interface{}{},
				"410": map[string]interface{}{},
				"411": map[string]interface{}{},
				"412": map[string]interface{}{},
				"413": map[string]interface{}{},
				"414": map[string]interface{}{},
				"415": map[string]interface{}{},
				"416": map[string]interface{}{},
				"417": map[string]interface{}{},
				"418": map[string]interface{}{},
				"419": map[string]interface{}{},
				"420": map[string]interface{}{},
				"421": map[string]interface{}{},
				"422": map[string]interface{}{},
				"423": map[string]interface{}{},
				"424": map[string]interface{}{},
				"425": map[string]interface{}{},
				"426": map[string]interface{}{},
				"427": map[string]interface{}{},
				"428": map[string]interface{}{},
				"429": map[string]interface{}{},
				"430": map[string]interface{}{},
				"431": map[string]interface{}{},
				"432": map[string]interface{}{},
				"433": map[string]interface{}{},
				"434": map[string]interface{}{},
				"435": map[string]interface{}{},
				"436": map[string]interface{}{},
				"437": map[string]interface{}{},
				"438": map[string]interface{}{},
				"439": map[string]interface{}{},
				"440": map[string]interface{}{},
				"441": map[string]interface{}{},
				"442": map[string]interface{}{},
				"443": map[string]interface{}{},
				"444": map[string]interface{}{},
				"445": map[string]interface{}{},
				"446": map[string]interface{}{},
				"447": map[string]interface{}{},
				"448": map[string]interface{}{},
				"449": map[string]interface{}{},
				"450": map[string]interface{}{},
				"451": map[string]interface{}{},
				"452": map[string]interface{}{},
				"453": map[string]interface{}{},
				"454": map[string]interface{}{},
			},
			ChannelDescription:                  map[string]interface{}{},
			ChannelLogoURL:                      map[string]interface{}{},
			ChannelAccountConnectionRedirectURL: map[string]interface{}{},
			Name:                                map[string]interface{}{},
			WebhookURL:                          map[string]interface{}{},
		},
	)
	if err != nil {
		var apierr *hubspotsdk.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestCustomChannelList(t *testing.T) {
	t.Skip("Prism tests are disabled")
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := hubspotsdk.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAccessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"),
	)
	_, err := client.Conversations.CustomChannels.List(context.TODO())
	if err != nil {
		var apierr *hubspotsdk.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestCustomChannelDelete(t *testing.T) {
	t.Skip("Prism tests are disabled")
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := hubspotsdk.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAccessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"),
	)
	err := client.Conversations.CustomChannels.Delete(context.TODO(), "channelId")
	if err != nil {
		var apierr *hubspotsdk.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestCustomChannelGet(t *testing.T) {
	t.Skip("Prism tests are disabled")
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := hubspotsdk.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAccessToken("pat-na1-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"),
	)
	_, err := client.Conversations.CustomChannels.Get(context.TODO(), "channelId")
	if err != nil {
		var apierr *hubspotsdk.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}
