// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package conversations_test

import (
	"context"
	"errors"
	"os"
	"testing"

	"github.com/stainless-sdks/hubspot-sdk-go"
	"github.com/stainless-sdks/hubspot-sdk-go/conversations"
	"github.com/stainless-sdks/hubspot-sdk-go/internal/testutil"
	"github.com/stainless-sdks/hubspot-sdk-go/option"
)

func TestCustomChannelNewWithOptionalParams(t *testing.T) {
	t.Skip("Prism tests are disabled")
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := hubspotsdk.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAccessToken("pat-na1-xxxxxxxx-xxxx"),
	)
	_, err := client.Conversations.CustomChannels.New(context.TODO(), conversations.CustomChannelNewParams{
		Capabilities: map[string]any{
			"0":   map[string]any{},
			"1":   map[string]any{},
			"2":   map[string]any{},
			"3":   map[string]any{},
			"4":   map[string]any{},
			"5":   map[string]any{},
			"6":   map[string]any{},
			"7":   map[string]any{},
			"8":   map[string]any{},
			"9":   map[string]any{},
			"10":  map[string]any{},
			"11":  map[string]any{},
			"12":  map[string]any{},
			"13":  map[string]any{},
			"14":  map[string]any{},
			"15":  map[string]any{},
			"16":  map[string]any{},
			"17":  map[string]any{},
			"18":  map[string]any{},
			"19":  map[string]any{},
			"20":  map[string]any{},
			"21":  map[string]any{},
			"22":  map[string]any{},
			"23":  map[string]any{},
			"24":  map[string]any{},
			"25":  map[string]any{},
			"26":  map[string]any{},
			"27":  map[string]any{},
			"28":  map[string]any{},
			"29":  map[string]any{},
			"30":  map[string]any{},
			"31":  map[string]any{},
			"32":  map[string]any{},
			"33":  map[string]any{},
			"34":  map[string]any{},
			"35":  map[string]any{},
			"36":  map[string]any{},
			"37":  map[string]any{},
			"38":  map[string]any{},
			"39":  map[string]any{},
			"40":  map[string]any{},
			"41":  map[string]any{},
			"42":  map[string]any{},
			"43":  map[string]any{},
			"44":  map[string]any{},
			"45":  map[string]any{},
			"46":  map[string]any{},
			"47":  map[string]any{},
			"48":  map[string]any{},
			"49":  map[string]any{},
			"50":  map[string]any{},
			"51":  map[string]any{},
			"52":  map[string]any{},
			"53":  map[string]any{},
			"54":  map[string]any{},
			"55":  map[string]any{},
			"56":  map[string]any{},
			"57":  map[string]any{},
			"58":  map[string]any{},
			"59":  map[string]any{},
			"60":  map[string]any{},
			"61":  map[string]any{},
			"62":  map[string]any{},
			"63":  map[string]any{},
			"64":  map[string]any{},
			"65":  map[string]any{},
			"66":  map[string]any{},
			"67":  map[string]any{},
			"68":  map[string]any{},
			"69":  map[string]any{},
			"70":  map[string]any{},
			"71":  map[string]any{},
			"72":  map[string]any{},
			"73":  map[string]any{},
			"74":  map[string]any{},
			"75":  map[string]any{},
			"76":  map[string]any{},
			"77":  map[string]any{},
			"78":  map[string]any{},
			"79":  map[string]any{},
			"80":  map[string]any{},
			"81":  map[string]any{},
			"82":  map[string]any{},
			"83":  map[string]any{},
			"84":  map[string]any{},
			"85":  map[string]any{},
			"86":  map[string]any{},
			"87":  map[string]any{},
			"88":  map[string]any{},
			"89":  map[string]any{},
			"90":  map[string]any{},
			"91":  map[string]any{},
			"92":  map[string]any{},
			"93":  map[string]any{},
			"94":  map[string]any{},
			"95":  map[string]any{},
			"96":  map[string]any{},
			"97":  map[string]any{},
			"98":  map[string]any{},
			"99":  map[string]any{},
			"100": map[string]any{},
			"101": map[string]any{},
			"102": map[string]any{},
			"103": map[string]any{},
			"104": map[string]any{},
			"105": map[string]any{},
			"106": map[string]any{},
			"107": map[string]any{},
			"108": map[string]any{},
			"109": map[string]any{},
			"110": map[string]any{},
			"111": map[string]any{},
			"112": map[string]any{},
			"113": map[string]any{},
			"114": map[string]any{},
			"115": map[string]any{},
			"116": map[string]any{},
			"117": map[string]any{},
			"118": map[string]any{},
			"119": map[string]any{},
			"120": map[string]any{},
			"121": map[string]any{},
			"122": map[string]any{},
			"123": map[string]any{},
			"124": map[string]any{},
			"125": map[string]any{},
			"126": map[string]any{},
			"127": map[string]any{},
			"128": map[string]any{},
			"129": map[string]any{},
			"130": map[string]any{},
			"131": map[string]any{},
			"132": map[string]any{},
			"133": map[string]any{},
			"134": map[string]any{},
			"135": map[string]any{},
			"136": map[string]any{},
			"137": map[string]any{},
			"138": map[string]any{},
			"139": map[string]any{},
			"140": map[string]any{},
			"141": map[string]any{},
			"142": map[string]any{},
			"143": map[string]any{},
			"144": map[string]any{},
			"145": map[string]any{},
			"146": map[string]any{},
			"147": map[string]any{},
			"148": map[string]any{},
			"149": map[string]any{},
			"150": map[string]any{},
			"151": map[string]any{},
			"152": map[string]any{},
			"153": map[string]any{},
			"154": map[string]any{},
			"155": map[string]any{},
			"156": map[string]any{},
			"157": map[string]any{},
			"158": map[string]any{},
			"159": map[string]any{},
			"160": map[string]any{},
			"161": map[string]any{},
			"162": map[string]any{},
			"163": map[string]any{},
			"164": map[string]any{},
			"165": map[string]any{},
			"166": map[string]any{},
			"167": map[string]any{},
			"168": map[string]any{},
			"169": map[string]any{},
			"170": map[string]any{},
			"171": map[string]any{},
			"172": map[string]any{},
			"173": map[string]any{},
			"174": map[string]any{},
			"175": map[string]any{},
			"176": map[string]any{},
			"177": map[string]any{},
			"178": map[string]any{},
			"179": map[string]any{},
			"180": map[string]any{},
			"181": map[string]any{},
			"182": map[string]any{},
			"183": map[string]any{},
			"184": map[string]any{},
			"185": map[string]any{},
			"186": map[string]any{},
			"187": map[string]any{},
			"188": map[string]any{},
			"189": map[string]any{},
			"190": map[string]any{},
			"191": map[string]any{},
			"192": map[string]any{},
			"193": map[string]any{},
			"194": map[string]any{},
			"195": map[string]any{},
			"196": map[string]any{},
			"197": map[string]any{},
			"198": map[string]any{},
			"199": map[string]any{},
			"200": map[string]any{},
			"201": map[string]any{},
			"202": map[string]any{},
			"203": map[string]any{},
			"204": map[string]any{},
			"205": map[string]any{},
			"206": map[string]any{},
			"207": map[string]any{},
			"208": map[string]any{},
			"209": map[string]any{},
			"210": map[string]any{},
			"211": map[string]any{},
			"212": map[string]any{},
			"213": map[string]any{},
			"214": map[string]any{},
			"215": map[string]any{},
			"216": map[string]any{},
			"217": map[string]any{},
			"218": map[string]any{},
			"219": map[string]any{},
			"220": map[string]any{},
			"221": map[string]any{},
			"222": map[string]any{},
			"223": map[string]any{},
			"224": map[string]any{},
			"225": map[string]any{},
			"226": map[string]any{},
			"227": map[string]any{},
			"228": map[string]any{},
			"229": map[string]any{},
			"230": map[string]any{},
			"231": map[string]any{},
			"232": map[string]any{},
			"233": map[string]any{},
			"234": map[string]any{},
			"235": map[string]any{},
			"236": map[string]any{},
			"237": map[string]any{},
			"238": map[string]any{},
			"239": map[string]any{},
			"240": map[string]any{},
			"241": map[string]any{},
			"242": map[string]any{},
			"243": map[string]any{},
			"244": map[string]any{},
			"245": map[string]any{},
			"246": map[string]any{},
			"247": map[string]any{},
			"248": map[string]any{},
			"249": map[string]any{},
			"250": map[string]any{},
			"251": map[string]any{},
			"252": map[string]any{},
			"253": map[string]any{},
			"254": map[string]any{},
			"255": map[string]any{},
			"256": map[string]any{},
			"257": map[string]any{},
			"258": map[string]any{},
			"259": map[string]any{},
			"260": map[string]any{},
			"261": map[string]any{},
			"262": map[string]any{},
			"263": map[string]any{},
			"264": map[string]any{},
			"265": map[string]any{},
			"266": map[string]any{},
			"267": map[string]any{},
			"268": map[string]any{},
			"269": map[string]any{},
			"270": map[string]any{},
			"271": map[string]any{},
			"272": map[string]any{},
			"273": map[string]any{},
			"274": map[string]any{},
			"275": map[string]any{},
			"276": map[string]any{},
			"277": map[string]any{},
			"278": map[string]any{},
			"279": map[string]any{},
			"280": map[string]any{},
			"281": map[string]any{},
			"282": map[string]any{},
			"283": map[string]any{},
			"284": map[string]any{},
			"285": map[string]any{},
			"286": map[string]any{},
			"287": map[string]any{},
			"288": map[string]any{},
			"289": map[string]any{},
			"290": map[string]any{},
			"291": map[string]any{},
			"292": map[string]any{},
			"293": map[string]any{},
			"294": map[string]any{},
			"295": map[string]any{},
			"296": map[string]any{},
			"297": map[string]any{},
			"298": map[string]any{},
			"299": map[string]any{},
			"300": map[string]any{},
			"301": map[string]any{},
			"302": map[string]any{},
			"303": map[string]any{},
			"304": map[string]any{},
			"305": map[string]any{},
			"306": map[string]any{},
			"307": map[string]any{},
			"308": map[string]any{},
			"309": map[string]any{},
			"310": map[string]any{},
			"311": map[string]any{},
			"312": map[string]any{},
			"313": map[string]any{},
			"314": map[string]any{},
			"315": map[string]any{},
			"316": map[string]any{},
			"317": map[string]any{},
			"318": map[string]any{},
			"319": map[string]any{},
			"320": map[string]any{},
			"321": map[string]any{},
			"322": map[string]any{},
			"323": map[string]any{},
			"324": map[string]any{},
			"325": map[string]any{},
			"326": map[string]any{},
			"327": map[string]any{},
			"328": map[string]any{},
			"329": map[string]any{},
			"330": map[string]any{},
			"331": map[string]any{},
			"332": map[string]any{},
			"333": map[string]any{},
			"334": map[string]any{},
			"335": map[string]any{},
			"336": map[string]any{},
			"337": map[string]any{},
			"338": map[string]any{},
			"339": map[string]any{},
			"340": map[string]any{},
			"341": map[string]any{},
			"342": map[string]any{},
			"343": map[string]any{},
			"344": map[string]any{},
			"345": map[string]any{},
			"346": map[string]any{},
			"347": map[string]any{},
			"348": map[string]any{},
			"349": map[string]any{},
			"350": map[string]any{},
			"351": map[string]any{},
			"352": map[string]any{},
			"353": map[string]any{},
			"354": map[string]any{},
			"355": map[string]any{},
			"356": map[string]any{},
			"357": map[string]any{},
			"358": map[string]any{},
			"359": map[string]any{},
			"360": map[string]any{},
			"361": map[string]any{},
			"362": map[string]any{},
			"363": map[string]any{},
			"364": map[string]any{},
			"365": map[string]any{},
			"366": map[string]any{},
			"367": map[string]any{},
			"368": map[string]any{},
			"369": map[string]any{},
			"370": map[string]any{},
			"371": map[string]any{},
			"372": map[string]any{},
			"373": map[string]any{},
			"374": map[string]any{},
			"375": map[string]any{},
			"376": map[string]any{},
			"377": map[string]any{},
			"378": map[string]any{},
			"379": map[string]any{},
			"380": map[string]any{},
			"381": map[string]any{},
			"382": map[string]any{},
			"383": map[string]any{},
			"384": map[string]any{},
			"385": map[string]any{},
			"386": map[string]any{},
			"387": map[string]any{},
			"388": map[string]any{},
			"389": map[string]any{},
			"390": map[string]any{},
			"391": map[string]any{},
			"392": map[string]any{},
			"393": map[string]any{},
			"394": map[string]any{},
			"395": map[string]any{},
			"396": map[string]any{},
			"397": map[string]any{},
			"398": map[string]any{},
			"399": map[string]any{},
			"400": map[string]any{},
			"401": map[string]any{},
			"402": map[string]any{},
			"403": map[string]any{},
			"404": map[string]any{},
			"405": map[string]any{},
			"406": map[string]any{},
			"407": map[string]any{},
			"408": map[string]any{},
			"409": map[string]any{},
			"410": map[string]any{},
			"411": map[string]any{},
			"412": map[string]any{},
			"413": map[string]any{},
			"414": map[string]any{},
			"415": map[string]any{},
			"416": map[string]any{},
			"417": map[string]any{},
			"418": map[string]any{},
			"419": map[string]any{},
			"420": map[string]any{},
			"421": map[string]any{},
			"422": map[string]any{},
			"423": map[string]any{},
			"424": map[string]any{},
			"425": map[string]any{},
			"426": map[string]any{},
			"427": map[string]any{},
			"428": map[string]any{},
			"429": map[string]any{},
			"430": map[string]any{},
			"431": map[string]any{},
			"432": map[string]any{},
			"433": map[string]any{},
			"434": map[string]any{},
			"435": map[string]any{},
			"436": map[string]any{},
			"437": map[string]any{},
			"438": map[string]any{},
			"439": map[string]any{},
			"440": map[string]any{},
			"441": map[string]any{},
			"442": map[string]any{},
			"443": map[string]any{},
			"444": map[string]any{},
			"445": map[string]any{},
			"446": map[string]any{},
			"447": map[string]any{},
			"448": map[string]any{},
			"449": map[string]any{},
			"450": map[string]any{},
			"451": map[string]any{},
			"452": map[string]any{},
			"453": map[string]any{},
			"454": map[string]any{},
		},
		Name:                                "name",
		ChannelAccountConnectionRedirectURL: hubspotsdk.String("channelAccountConnectionRedirectUrl"),
		ChannelDescription:                  hubspotsdk.String("channelDescription"),
		ChannelLogoURL:                      hubspotsdk.String("channelLogoUrl"),
		WebhookURL:                          hubspotsdk.String("webhookUrl"),
	})
	if err != nil {
		var apierr *hubspotsdk.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestCustomChannelUpdateWithOptionalParams(t *testing.T) {
	t.Skip("Prism tests are disabled")
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := hubspotsdk.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAccessToken("pat-na1-xxxxxxxx-xxxx"),
	)
	_, err := client.Conversations.CustomChannels.Update(
		context.TODO(),
		"channelId",
		conversations.CustomChannelUpdateParams{
			Capabilities: map[string]any{
				"0":   map[string]any{},
				"1":   map[string]any{},
				"2":   map[string]any{},
				"3":   map[string]any{},
				"4":   map[string]any{},
				"5":   map[string]any{},
				"6":   map[string]any{},
				"7":   map[string]any{},
				"8":   map[string]any{},
				"9":   map[string]any{},
				"10":  map[string]any{},
				"11":  map[string]any{},
				"12":  map[string]any{},
				"13":  map[string]any{},
				"14":  map[string]any{},
				"15":  map[string]any{},
				"16":  map[string]any{},
				"17":  map[string]any{},
				"18":  map[string]any{},
				"19":  map[string]any{},
				"20":  map[string]any{},
				"21":  map[string]any{},
				"22":  map[string]any{},
				"23":  map[string]any{},
				"24":  map[string]any{},
				"25":  map[string]any{},
				"26":  map[string]any{},
				"27":  map[string]any{},
				"28":  map[string]any{},
				"29":  map[string]any{},
				"30":  map[string]any{},
				"31":  map[string]any{},
				"32":  map[string]any{},
				"33":  map[string]any{},
				"34":  map[string]any{},
				"35":  map[string]any{},
				"36":  map[string]any{},
				"37":  map[string]any{},
				"38":  map[string]any{},
				"39":  map[string]any{},
				"40":  map[string]any{},
				"41":  map[string]any{},
				"42":  map[string]any{},
				"43":  map[string]any{},
				"44":  map[string]any{},
				"45":  map[string]any{},
				"46":  map[string]any{},
				"47":  map[string]any{},
				"48":  map[string]any{},
				"49":  map[string]any{},
				"50":  map[string]any{},
				"51":  map[string]any{},
				"52":  map[string]any{},
				"53":  map[string]any{},
				"54":  map[string]any{},
				"55":  map[string]any{},
				"56":  map[string]any{},
				"57":  map[string]any{},
				"58":  map[string]any{},
				"59":  map[string]any{},
				"60":  map[string]any{},
				"61":  map[string]any{},
				"62":  map[string]any{},
				"63":  map[string]any{},
				"64":  map[string]any{},
				"65":  map[string]any{},
				"66":  map[string]any{},
				"67":  map[string]any{},
				"68":  map[string]any{},
				"69":  map[string]any{},
				"70":  map[string]any{},
				"71":  map[string]any{},
				"72":  map[string]any{},
				"73":  map[string]any{},
				"74":  map[string]any{},
				"75":  map[string]any{},
				"76":  map[string]any{},
				"77":  map[string]any{},
				"78":  map[string]any{},
				"79":  map[string]any{},
				"80":  map[string]any{},
				"81":  map[string]any{},
				"82":  map[string]any{},
				"83":  map[string]any{},
				"84":  map[string]any{},
				"85":  map[string]any{},
				"86":  map[string]any{},
				"87":  map[string]any{},
				"88":  map[string]any{},
				"89":  map[string]any{},
				"90":  map[string]any{},
				"91":  map[string]any{},
				"92":  map[string]any{},
				"93":  map[string]any{},
				"94":  map[string]any{},
				"95":  map[string]any{},
				"96":  map[string]any{},
				"97":  map[string]any{},
				"98":  map[string]any{},
				"99":  map[string]any{},
				"100": map[string]any{},
				"101": map[string]any{},
				"102": map[string]any{},
				"103": map[string]any{},
				"104": map[string]any{},
				"105": map[string]any{},
				"106": map[string]any{},
				"107": map[string]any{},
				"108": map[string]any{},
				"109": map[string]any{},
				"110": map[string]any{},
				"111": map[string]any{},
				"112": map[string]any{},
				"113": map[string]any{},
				"114": map[string]any{},
				"115": map[string]any{},
				"116": map[string]any{},
				"117": map[string]any{},
				"118": map[string]any{},
				"119": map[string]any{},
				"120": map[string]any{},
				"121": map[string]any{},
				"122": map[string]any{},
				"123": map[string]any{},
				"124": map[string]any{},
				"125": map[string]any{},
				"126": map[string]any{},
				"127": map[string]any{},
				"128": map[string]any{},
				"129": map[string]any{},
				"130": map[string]any{},
				"131": map[string]any{},
				"132": map[string]any{},
				"133": map[string]any{},
				"134": map[string]any{},
				"135": map[string]any{},
				"136": map[string]any{},
				"137": map[string]any{},
				"138": map[string]any{},
				"139": map[string]any{},
				"140": map[string]any{},
				"141": map[string]any{},
				"142": map[string]any{},
				"143": map[string]any{},
				"144": map[string]any{},
				"145": map[string]any{},
				"146": map[string]any{},
				"147": map[string]any{},
				"148": map[string]any{},
				"149": map[string]any{},
				"150": map[string]any{},
				"151": map[string]any{},
				"152": map[string]any{},
				"153": map[string]any{},
				"154": map[string]any{},
				"155": map[string]any{},
				"156": map[string]any{},
				"157": map[string]any{},
				"158": map[string]any{},
				"159": map[string]any{},
				"160": map[string]any{},
				"161": map[string]any{},
				"162": map[string]any{},
				"163": map[string]any{},
				"164": map[string]any{},
				"165": map[string]any{},
				"166": map[string]any{},
				"167": map[string]any{},
				"168": map[string]any{},
				"169": map[string]any{},
				"170": map[string]any{},
				"171": map[string]any{},
				"172": map[string]any{},
				"173": map[string]any{},
				"174": map[string]any{},
				"175": map[string]any{},
				"176": map[string]any{},
				"177": map[string]any{},
				"178": map[string]any{},
				"179": map[string]any{},
				"180": map[string]any{},
				"181": map[string]any{},
				"182": map[string]any{},
				"183": map[string]any{},
				"184": map[string]any{},
				"185": map[string]any{},
				"186": map[string]any{},
				"187": map[string]any{},
				"188": map[string]any{},
				"189": map[string]any{},
				"190": map[string]any{},
				"191": map[string]any{},
				"192": map[string]any{},
				"193": map[string]any{},
				"194": map[string]any{},
				"195": map[string]any{},
				"196": map[string]any{},
				"197": map[string]any{},
				"198": map[string]any{},
				"199": map[string]any{},
				"200": map[string]any{},
				"201": map[string]any{},
				"202": map[string]any{},
				"203": map[string]any{},
				"204": map[string]any{},
				"205": map[string]any{},
				"206": map[string]any{},
				"207": map[string]any{},
				"208": map[string]any{},
				"209": map[string]any{},
				"210": map[string]any{},
				"211": map[string]any{},
				"212": map[string]any{},
				"213": map[string]any{},
				"214": map[string]any{},
				"215": map[string]any{},
				"216": map[string]any{},
				"217": map[string]any{},
				"218": map[string]any{},
				"219": map[string]any{},
				"220": map[string]any{},
				"221": map[string]any{},
				"222": map[string]any{},
				"223": map[string]any{},
				"224": map[string]any{},
				"225": map[string]any{},
				"226": map[string]any{},
				"227": map[string]any{},
				"228": map[string]any{},
				"229": map[string]any{},
				"230": map[string]any{},
				"231": map[string]any{},
				"232": map[string]any{},
				"233": map[string]any{},
				"234": map[string]any{},
				"235": map[string]any{},
				"236": map[string]any{},
				"237": map[string]any{},
				"238": map[string]any{},
				"239": map[string]any{},
				"240": map[string]any{},
				"241": map[string]any{},
				"242": map[string]any{},
				"243": map[string]any{},
				"244": map[string]any{},
				"245": map[string]any{},
				"246": map[string]any{},
				"247": map[string]any{},
				"248": map[string]any{},
				"249": map[string]any{},
				"250": map[string]any{},
				"251": map[string]any{},
				"252": map[string]any{},
				"253": map[string]any{},
				"254": map[string]any{},
				"255": map[string]any{},
				"256": map[string]any{},
				"257": map[string]any{},
				"258": map[string]any{},
				"259": map[string]any{},
				"260": map[string]any{},
				"261": map[string]any{},
				"262": map[string]any{},
				"263": map[string]any{},
				"264": map[string]any{},
				"265": map[string]any{},
				"266": map[string]any{},
				"267": map[string]any{},
				"268": map[string]any{},
				"269": map[string]any{},
				"270": map[string]any{},
				"271": map[string]any{},
				"272": map[string]any{},
				"273": map[string]any{},
				"274": map[string]any{},
				"275": map[string]any{},
				"276": map[string]any{},
				"277": map[string]any{},
				"278": map[string]any{},
				"279": map[string]any{},
				"280": map[string]any{},
				"281": map[string]any{},
				"282": map[string]any{},
				"283": map[string]any{},
				"284": map[string]any{},
				"285": map[string]any{},
				"286": map[string]any{},
				"287": map[string]any{},
				"288": map[string]any{},
				"289": map[string]any{},
				"290": map[string]any{},
				"291": map[string]any{},
				"292": map[string]any{},
				"293": map[string]any{},
				"294": map[string]any{},
				"295": map[string]any{},
				"296": map[string]any{},
				"297": map[string]any{},
				"298": map[string]any{},
				"299": map[string]any{},
				"300": map[string]any{},
				"301": map[string]any{},
				"302": map[string]any{},
				"303": map[string]any{},
				"304": map[string]any{},
				"305": map[string]any{},
				"306": map[string]any{},
				"307": map[string]any{},
				"308": map[string]any{},
				"309": map[string]any{},
				"310": map[string]any{},
				"311": map[string]any{},
				"312": map[string]any{},
				"313": map[string]any{},
				"314": map[string]any{},
				"315": map[string]any{},
				"316": map[string]any{},
				"317": map[string]any{},
				"318": map[string]any{},
				"319": map[string]any{},
				"320": map[string]any{},
				"321": map[string]any{},
				"322": map[string]any{},
				"323": map[string]any{},
				"324": map[string]any{},
				"325": map[string]any{},
				"326": map[string]any{},
				"327": map[string]any{},
				"328": map[string]any{},
				"329": map[string]any{},
				"330": map[string]any{},
				"331": map[string]any{},
				"332": map[string]any{},
				"333": map[string]any{},
				"334": map[string]any{},
				"335": map[string]any{},
				"336": map[string]any{},
				"337": map[string]any{},
				"338": map[string]any{},
				"339": map[string]any{},
				"340": map[string]any{},
				"341": map[string]any{},
				"342": map[string]any{},
				"343": map[string]any{},
				"344": map[string]any{},
				"345": map[string]any{},
				"346": map[string]any{},
				"347": map[string]any{},
				"348": map[string]any{},
				"349": map[string]any{},
				"350": map[string]any{},
				"351": map[string]any{},
				"352": map[string]any{},
				"353": map[string]any{},
				"354": map[string]any{},
				"355": map[string]any{},
				"356": map[string]any{},
				"357": map[string]any{},
				"358": map[string]any{},
				"359": map[string]any{},
				"360": map[string]any{},
				"361": map[string]any{},
				"362": map[string]any{},
				"363": map[string]any{},
				"364": map[string]any{},
				"365": map[string]any{},
				"366": map[string]any{},
				"367": map[string]any{},
				"368": map[string]any{},
				"369": map[string]any{},
				"370": map[string]any{},
				"371": map[string]any{},
				"372": map[string]any{},
				"373": map[string]any{},
				"374": map[string]any{},
				"375": map[string]any{},
				"376": map[string]any{},
				"377": map[string]any{},
				"378": map[string]any{},
				"379": map[string]any{},
				"380": map[string]any{},
				"381": map[string]any{},
				"382": map[string]any{},
				"383": map[string]any{},
				"384": map[string]any{},
				"385": map[string]any{},
				"386": map[string]any{},
				"387": map[string]any{},
				"388": map[string]any{},
				"389": map[string]any{},
				"390": map[string]any{},
				"391": map[string]any{},
				"392": map[string]any{},
				"393": map[string]any{},
				"394": map[string]any{},
				"395": map[string]any{},
				"396": map[string]any{},
				"397": map[string]any{},
				"398": map[string]any{},
				"399": map[string]any{},
				"400": map[string]any{},
				"401": map[string]any{},
				"402": map[string]any{},
				"403": map[string]any{},
				"404": map[string]any{},
				"405": map[string]any{},
				"406": map[string]any{},
				"407": map[string]any{},
				"408": map[string]any{},
				"409": map[string]any{},
				"410": map[string]any{},
				"411": map[string]any{},
				"412": map[string]any{},
				"413": map[string]any{},
				"414": map[string]any{},
				"415": map[string]any{},
				"416": map[string]any{},
				"417": map[string]any{},
				"418": map[string]any{},
				"419": map[string]any{},
				"420": map[string]any{},
				"421": map[string]any{},
				"422": map[string]any{},
				"423": map[string]any{},
				"424": map[string]any{},
				"425": map[string]any{},
				"426": map[string]any{},
				"427": map[string]any{},
				"428": map[string]any{},
				"429": map[string]any{},
				"430": map[string]any{},
				"431": map[string]any{},
				"432": map[string]any{},
				"433": map[string]any{},
				"434": map[string]any{},
				"435": map[string]any{},
				"436": map[string]any{},
				"437": map[string]any{},
				"438": map[string]any{},
				"439": map[string]any{},
				"440": map[string]any{},
				"441": map[string]any{},
				"442": map[string]any{},
				"443": map[string]any{},
				"444": map[string]any{},
				"445": map[string]any{},
				"446": map[string]any{},
				"447": map[string]any{},
				"448": map[string]any{},
				"449": map[string]any{},
				"450": map[string]any{},
				"451": map[string]any{},
				"452": map[string]any{},
				"453": map[string]any{},
				"454": map[string]any{},
			},
			ChannelDescription:                  map[string]any{},
			ChannelLogoURL:                      map[string]any{},
			ChannelAccountConnectionRedirectURL: map[string]any{},
			Name:                                map[string]any{},
			WebhookURL:                          map[string]any{},
		},
	)
	if err != nil {
		var apierr *hubspotsdk.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestCustomChannelList(t *testing.T) {
	t.Skip("Prism tests are disabled")
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := hubspotsdk.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAccessToken("pat-na1-xxxxxxxx-xxxx"),
	)
	_, err := client.Conversations.CustomChannels.List(context.TODO())
	if err != nil {
		var apierr *hubspotsdk.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestCustomChannelDelete(t *testing.T) {
	t.Skip("Prism tests are disabled")
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := hubspotsdk.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAccessToken("pat-na1-xxxxxxxx-xxxx"),
	)
	err := client.Conversations.CustomChannels.Delete(context.TODO(), "channelId")
	if err != nil {
		var apierr *hubspotsdk.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}

func TestCustomChannelGet(t *testing.T) {
	t.Skip("Prism tests are disabled")
	baseURL := "http://localhost:4010"
	if envURL, ok := os.LookupEnv("TEST_API_BASE_URL"); ok {
		baseURL = envURL
	}
	if !testutil.CheckTestServer(t, baseURL) {
		return
	}
	client := hubspotsdk.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAccessToken("pat-na1-xxxxxxxx-xxxx"),
	)
	_, err := client.Conversations.CustomChannels.Get(context.TODO(), "channelId")
	if err != nil {
		var apierr *hubspotsdk.Error
		if errors.As(err, &apierr) {
			t.Log(string(apierr.DumpRequest(true)))
		}
		t.Fatalf("err should be nil: %s", err.Error())
	}
}
